#!/bin/sh

PATH=./:$PATH

L_SRV=login-server
C_SRV=char-server
M_SRV=map-server

print_start() {
	echo "Copyright - 2016 Spell Master Games"
	echo "Emulador Iniciando..."
	echo ""
	echo "Verificando..."
}

check_files() {
	for i in ${L_SRV} ${C_SRV} ${M_SRV}
	do
		if [ ! -f ./$i ]; then
			echo "$i não existe, ou não pode executar."
			echo "Parado. Confira seu compilador."
			exit 1;
		fi
	done
	echo "Checagem completa."
	echo "Todos requisitos funcionando!"
}

case $1 in
	'start')
print_start
check_files
exec ./${L_SRV}&
echo $! > .${L_SRV}.pid
exec ./${C_SRV}&
echo $! > .${C_SRV}.pid
exec ./${M_SRV}&
echo $! > .${M_SRV}.pid
echo "Iniciando....."
;;
'stop')
for i in .${L_SRV}.pid .${C_SRV}.pid .${M_SRV}.pid
do
	if [ -e ./$i ]; then
		kill $(cat $i)
		rm $i
	fi
done
;;
'restart')
$0 stop
$0 start
;;
*)
echo "Usos: servidor { start | stop | restart }"
;;
esac
