/*
* ARQUIVO SERÁ REMOVIDO E TODOS SEUS VALORES FIXADOS NO CÓDIGO!
* NÃO ALTERAR NADA AQUI PARA EVITAR BUGS NO EMULADOR!!!!
 */

#ifndef CONFIG_RENEWAL_H
#define CONFIG_RENEWAL_H
#define RENEWAL
#define RENEWAL_CAST
#define RENEWAL_DROP
#define RENEWAL_EXP
#define RENEWAL_LVDMG
#define RENEWAL_EDP
#endif