/*--------------------------------------------------------------------*\
|                ____                     _                            |
|               /    |                   | |_                          |
|              /     |_ __ ____  __ _  __| |_  __ _                    |
|             /  /|  | '__/  __|/ _` |/ _  | |/ _` |                   |
|            /  __   | | |  |__| (_| | (_| | | (_| |                   |
|           /  /  |  |_|  \____|\__,_|\__,_|_|\__,_|                   |
|          /__/   |__|  [ Ragnarok Emulator ]                          |
|                                                                      |
|----------------------------------------------------------------------|
| - Descrição: Configuação de definições Gerais                        |
\*--------------------------------------------------------------------*/

battle_configuration: {
	min_hair_style: 0
	max_hair_style: 29
	min_hair_color: 0
	max_hair_color: 8
	min_cloth_color: 0
	max_cloth_color: 4
	min_body_style: 0
	max_body_style: 4
	packet_obfuscation: 0
	min_chat_delay: 0
	hide_woe_damage: true
	pet_hair_style: 100
	area_size: 14
	max_walk_path: 17
	client_limit_unit_lv: 0
	wedding_modifydisplay: false
	save_clothcolor: true
	save_body_style: false
	wedding_ignorepalette: false
	xmas_ignorepalette: false
	summer_ignorepalette: false
	hanbok_ignorepalette: false
	display_version: false
	display_hallucination: false
	display_status_timers: true
	client_reshuffle_dice: true
	client_sort_storage: false
	client_accept_chatdori: 0
	client_emblem_max_blank_percent: 100
	item_auto_get: false
	flooritem_lifetime: 60000
	item_first_get_time: 3000
	item_second_get_time: 1000
	item_third_get_time: 1000
	mvp_item_first_get_time: 10000
	mvp_item_second_get_time: 10000
	mvp_item_third_get_time: 2000
	drop_rate0item: false
	drops_by_luk: 0
	drops_by_luk2: 0
	alchemist_summon_reward: 1
	rare_drop_announce: 0
	multi_level_up: true
	max_exp_gain_rate: 0
	exp_calc_type: 0
	exp_bonus_attacker: 25
	exp_bonus_max_attacker: 12
	heal_exp: 0
	resurrection_exp: 0
	shop_exp: 0
	pvp_exp: false
	death_penalty_type: 2
	death_penalty_base: 100
	death_penalty_job: 100
	zeny_penalty: 0
	disp_experience: false
	disp_zeny: false
	use_statpoint_table: true
	atcommand_spawn_quantity_limit: 100
	atcommand_slave_clone_limit: 25
	partial_name_scan: false
	atcommand_max_stat_bypass: false
	ban_hack_trade: 5
	atcommand_mobinfo_type: 0
	gm_ignore_warpable_area: 2
	atcommand_levelup_events: false
	guild_emperium_check: true
	guild_exp_limit: 50
	guild_max_castles: 0
	guild_skill_relog_delay: false
	castle_defense_rate: 100
	gvg_flee_penalty: 20
	require_glory_guild: false
	max_guild_alliance: 3
	guild_notice_changemap: 0
	guild_castle_invite: false
	guild_castle_expulsion: false
	hom_setting: 0x1D
	homunculus_friendly_rate: 100
	hom_rename: false
	hvan_explosion_intimate: 45000
	homunculus_show_growth: true
	homunculus_autoloot: true
	homunculus_auto_vapor: true
	vending_max_value: 1000000000
	vending_over_max: false
	vending_tax: 0
	buyer_name: true
	weapon_produce_rate: 100
	potion_produce_rate: 100
	produce_item_name_input: 0x25
	dead_branch_active: true
	random_monster_checklv: false
	ignore_items_gender: true
	item_check: false
	item_use_interval: 100
	cashfood_use_interval: 60000
	autospell_stacking: false
	item_restricted_consumption_type: true
	item_enabled_npc: true
	unequip_restricted_equipment: 3
	pk_mode: 0
	manner_system: 31
	pk_min_level: 55
	pk_level_range: 0
	skill_log: false
	battle_log: false
	etc_log: false
	warp_point_debug: false
	night_at_start: false
	day_duration: 1800000
	night_duration: 1800000
	duel_allow_pvp: false
	duel_allow_gvg: false
	duel_allow_teleport: false
	duel_autoleave_when_die: true
	duel_time_interval: 60
	duel_only_on_same_map: false
	official_cell_stack_limit: 1
	custom_cell_stack_limit: 1
	check_occupied_cells: true
	at_mapflag: false
	at_timeout: 2880
	auction_feeperhour: 12000
	auction_maximumprice: 500000000
	searchstore_querydelay: 10
	searchstore_maxresults: 30
	cashshop_show_points: false
	mail_show_status: 2
	mon_trans_disable_in_gvg: false
	case_sensitive_aegisnames: true
	mvp_hp_rate: 100
	monster_hp_rate: 100
	monster_max_aspd: 199
	monster_ai: 0
	monster_chase_refresh: 3
	mob_warp: 0
	mob_active_time: 0
	boss_active_time: 0
	view_range_rate: 100
	chase_range_rate: 100
	monster_active_enable: true
	override_mob_names: 0
	monster_damage_delay_rate: 100
	monster_loot_type: 0
	mob_skill_rate: 100
	mob_skill_delay: 100
	mob_count_rate: 100
	mob_spawn_delay: 100
	plant_spawn_delay: 100
	boss_spawn_delay: 100
	no_spawn_on_player: 0
	force_random_spawn: false
	slaves_inherit_mode: 2
	slaves_inherit_speed: 3
	summons_trigger_autospells: true
	retaliate_to_master: true
	mob_changetarget_byskill: false
	monster_class_change_full_recover: true
	show_mob_info: 4
	zeny_from_mobs: false
	mobs_level_up: false
	mobs_level_up_exp_rate: 1
	dynamic_mobs: true
	mob_remove_damaged: false
	mob_remove_delay: 300000
	mob_npc_event_type: 1
	ksprotection: 0
	mob_slave_keep_target: true
	mvp_tomb_enabled: true
	show_monster_hp_bar: false
	mob_size_influence: false
	mob_icewall_walk_block: 220
	boss_icewall_walk_block: 1
	show_steal_in_same_party: false
	party_update_interval: 1000
	party_hp_mode: 0
	show_party_share_picker: true
	show_picker_item_type: 112
	party_item_share_type: 0
	idle_no_share: 0
	party_even_share_bonus: 0
	display_party_name: true
	pet_catch_rate: 100
	pet_rename: false
	pet_friendly_rate: 100
	pet_hungry_delay_rate: 100
	pet_hungry_friendly_decrease: 5
	pet_equip_required: true
	pet_attack_support: false
	pet_damage_support: false
	pet_support_min_friendly: 900
	pet_equip_min_friendly: 900
	pet_status_support: false
	pet_support_rate: 100
	pet_attack_exp_to_master: false
	pet_attack_exp_rate: 100
	pet_lv_rate: 0
	pet_max_stats: 99
	pet_max_atk1: 500
	pet_max_atk2: 1000
	pet_disable_in_gvg: true
	left_cardfix_to_right: true
	restart_hp_rate: 0
	restart_sp_rate: 0
	player_skillfree: false
	player_skillup_limit: true
	quest_skill_learn: false
	quest_skill_reset: false
	basic_skill_check: true
	player_invincible_time: 5000
	fix_warp_hit_delay_abuse: false
	natural_healhp_interval: 6000
	natural_healsp_interval: 8000
	natural_heal_skill_interval: 10000
	natural_heal_weight_rate: 50
	max_walk_speed: 300
	over_def_bonus: 0
	max_cart_weight: 8000
	prevent_logout: 10000
	show_hp_sp_drain: false
	show_hp_sp_gain: true
	show_katar_crit_bonus: false
	friend_auto_add: true
	invite_request_check: true
	bone_drop: 0
	character_size: 0
	idle_no_autoloot: 0
	min_npc_vendchat_distance: 3
	vendchat_near_hiddennpc: false
	snovice_call_type: 0
	idletime_criteria: 0x1F
	costume_refine_def: false
	shadow_refine_def: false
	shadow_refine_atk: false
	player_warp_keep_direction: false
	delay_dependon_dex: false
	delay_dependon_agi: false
	default_walk_delay: 300
	no_skill_delay: 2
	castrate_dex_scale: 150
	vcast_stat_scale: 530
	skill_amotion_leniency: 90
	skill_delay_attack_enable: true
	skill_add_range: 0
	skill_out_range_consume: false
	skillrange_by_distance: 14
	skillrange_from_weapon: 0
	skill_caster_check: true
	clear_skills_on_death: 0
	clear_skills_on_warp: 15
	defunit_not_enemy: false
	auto_counter_type: 15
	skill_reiteration: 0
	skill_nofootset: 1
	gvg_traps_target_all: 1
	traps_setting: 0
	summon_flora_setting: 3
	song_timer_reset: 0
	skill_wall_check: true
	player_cloak_check_type: 1
	monster_cloak_check_type: 4
	land_skill_limit: 9
	display_skill_fail: 0
	chat_warpportal: false
	sense_type: 1
	finger_offensive_type: 0
	gx_allhit: false
	gx_disptype: 1
	devotion_level_difference: 10
	player_skill_partner_check: true
	skill_removetrap_type: 0
	backstab_bow_penalty: true
	skill_steal_max_tries: 0
	copyskill_restrict: 2
	berserk_cancels_buffs: false
	max_heal: 9999
	max_heal_lv: 11
	emergency_call: 11
	guild_aura: 31
	skip_teleport_lv1_menu: true
	allow_skill_without_day: false
	allow_es_magic_player: false
	sg_miracle_skill_ratio: 2
	sg_miracle_skill_duration: 3600000
	sg_angel_skill_ratio: 10
	skill_add_heal_rate: 7
	eq_single_target_reflectable: true
	invincible_nodamage: false
	dancing_weaponswitch_fix: true
	skill_trap_type: 0
	mob_max_skilllvl: 100
	bowling_bash_area: 0
	stormgust_knockback: true
	enable_baseatk: 9
	enable_perfect_flee: 1
	enable_critical: 17
	mob_critical_rate: 100
	critical_rate: 100
	attack_walk_delay: 15
	pc_damage_walk_delay_rate: 20
	damage_walk_delay_rate: 100
	multihit_delay: 80
	player_damage_delay_rate: 100
	undead_detect_type: 0
	attribute_recover: false
	min_hitrate: 5
	max_hitrate: 100
	agi_penalty_type: 1
	agi_penalty_target: 1
	agi_penalty_count: 3
	agi_penalty_num: 10
	vit_penalty_type: 1
	vit_penalty_target: 1
	vit_penalty_count: 3
	vit_penalty_num: 5
	weapon_defense_type: 0
	magic_defense_type: 0
	attack_direction_change: 0
	attack_attr_none: 14
	equip_natural_break_rate: 0
	equip_self_break_rate: 100
	equip_skill_break_rate: 100
	delay_battle_damage: true
	arrow_decrement: 1
	autospell_check_range: false
	knockback_left: true
	snap_dodge: false
	status_cast_cancel: 0
	pc_status_def_rate: 100
	mob_status_def_rate: 100
	pc_max_status_def: 100
	mob_max_status_def: 100
	bg_flee_penalty: 20
	bg_update_interval: 1000
	@include "Config/Common/Feature.cs"
}